[package]
name = "nntp-rs-history"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]

[dependencies]
lazy_static = "1.0.0"
log = "0.3"
time = "0.1.39"
linked-hash-map = "0.5.1"
