[package]
name = "storage"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.0.0"
log = "0.3"
time = "0.1.39"
linked-hash-map = "0.5.1"
memchr = "2.0.1"
libc = "0.2"

