#!/bin/sh

#DEBHELPER#

set -e

# Create manually, so we can set ownership to news, and so
# that the files do not get removed at package removal time.
if [ ! -d /var/spool/news ]
then
	install -d -o news -g news -m 755 /var/spool/news
	install -d -o news -g news -m 755 /var/spool/news/articles
fi
if [ ! -d /var/lib/news ]
then
	install -d -o news -g news -m 755 /var/lib/news
fi

# make sure we can write to the log dir.
chown news:news /var/log/news

if systemctl -q is-active nntp-rs
then
	systemctl restart nntp-rs
fi

