[server]
listen = "[::]:1119"
threads = 1

[history]
path = "/home/mikevs/tmp/dhistory"
backend = "diablo"
threads = 1

[spool.0]
backend = "diablo"
path = "/news/spool/news/P.00"
minfree = "10G"

[spool.1]
backend = "diablo"
path = "/news/spool/news/P.01"
minfree = "10G"

[spool.2]
backend = "diablo"
path = "/news/spool/news/P.02"
minfree = "10G"

[[metaspool]]
spool = [ 1, 2, 3 ]
groups = [ "*" ]
maxsize = "64K"
reallocint = "10m"

