#! /bin/sh
#
# logcompress	Compresses the incoming.log.$DATE files, except the
#		current one, and removes old files.
#

DIR=/var/log/news
KEEPDAYS=3
COMPRESS="/bin/gzip -f"

set -e
cd $DIR
umask 022
find . -name 'incoming.log.????????.*' -mmin +$((1440*$KEEPDAYS)) -delete

DATE=$(date +%Y%m%d)
find . -name 'incoming.log.????????' |
while read LOG
do
	case $LOG in
		*.$DATE) ;;
		*.gz|*.bz2|*.xz) ;;
		*)
			$COMPRESS $LOG
			;;
	esac
done

